### ISSUE TITLE
Package?

### ISSUE THREAD

**Issue by VincentvD** [klutchdev/klutch-fire-hooks#1]
Considering react-fire-hooks is pretty dormant. Any chances you're packaging this as a new v9 compatible lib?

**Comment by klutchdev** [comment]
I have no idea why I didn't see this!!!
I can totally do that

**Comment by VincentvD** [comment]
No problem, didn't want to impose anything but I think a lot of people would benefit from this. I saw another PR in the original repo here:
https://github.com/CSFrequency/react-firebase-hooks/pull/174
I have been testing with it but I'm afraid it'll never be merged. Perhaps that time and energy is better spent here. 

If you're going forward with this repo and a package, I'll be happy to test it out!

**Comment by klutchdev** [comment]
I put a hold on it only because they wrote the library- I didn't want to be THAT guy by just taking the whole thing and re-releasing it with only a few changes under my name lol. I named it that because I used it in a personal project, and wanted to make sure it was indeed separate. 

It's been quite a while now at this point, and right off the top of my head I can think of at least 20 people that have been severely inconvenienced by this since the update.... So, I'm just gonna get everything updated, buttoned up quick, and ready to rock under this name for the time being. If they decide to finally merge, I'll take this one down- but in the meantime, it will be done. It has to be!!!
Thanks for reaching out, I'll be in touch soon!

**Comment by andipaetzold** [comment]
Hey @klutchdev :wave:,

I am the author of the original PR and rewrote the original library and released it as a new one.
Could you have a look at https://github.com/CSFrequency/react-firebase-hooks/pull/174#issuecomment-945017981
I want to avoid having two packages with almost identical features and hooks.

**Comment by klutchdev** [comment]
Absolutely! Thank you very much! 😊
